import RootAboutPage from '@/components/about/RootAboutPage';

export const metadata = {
    title: 'About WebBriks: About Web Briks LLC – Expert Outsourcing for Photo Editing & Creative Design',
    description: 'Generated by create next app',
};

export default async function page() {
    return <RootAboutPage />;
}
