import RootAboutPage from '@/components/about/RootAboutPage';

export const metadata = {
    title: 'About | Webbriks',
    description: 'Generated by create next app',
};

export default async function page() {
    return <RootAboutPage />;
}
