import RootWebDesignDevelopmentService from '@/components/services/web-design-and-development/RootWebDesignDevelopmentService';

export const metadata = {
    title: 'Web Design & Development Service | Webbriks',
    description: 'Generated by create next app',
};

export default async function page() {
    return <RootWebDesignDevelopmentService />;
}
