import RootContactPage from '@/components/contact/RootContactPage';

export const metadata = {
    title: 'Contact | Webbriks',
    description: 'Generated by create next app',
};

export default async function page() {
    return <RootContactPage />;
}
