export const teamMembers = [
    {
        id: 'WB0001',
        name: 'Md. Ashaduzzaman',
        designation: 'CEO and Founder',
        image: '/about/boss/asad.png',
        description: `Md Ashaduzzaman drives the company's vision with profound strategic oversight of all innovations and services. He ensures seamless execution, constantly motivating the team to push boundaries and deliver excellence in services. His leadership fuels growth, inspiring every team member to achieve new heights.`,
    },
    {
        id: 'WB0002',
        name: 'Md. Ariful Islam',
        designation: 'Creative Director',
        image: '/about/boss/arif.png',
        description: `Md. Ariful Islam plays a vital role in shaping the company's growth and strategic direction. His dedication and leadership contribute to WebBriks' continuous success in the global market.`,
    },
    {
        id: 'WB0003',
        name: 'Md. Masum Kamal',
        designation: 'Head of Production',
        image: '/about/boss/dulu.png',
        description: `Md. Masum Kamal ensures exceptional client satisfaction through efficient communication and service delivery. He leads the support team in providing seamless assistance for services. His commitment to excellence helps WebBriks build long-term relationships with global clients.`,
    },
    {
        id: 'WB0004',
        name: 'Md. Kobir Hosain',
        designation: 'Technical Advisor',
        image: '/about/boss/kobir.png',
        description: `Md. Kobir Hosain plays a key role in driving the company's growth and innovation. He contributes to the strategic development of the company.`,
    },
    {
        id: 'WB0005',
        name: 'Md. Oazed Akondo',
        designation: 'HR Manager',
        image: '/about/team-member/oazed-akondo.png',
        description: `Md. Oazed Akondo manages finances and keeps office operations running smoothly. His hard work helps WebBriks provide excellent service to its clients. He also works hard to keep the office environment working-friendly.`,
    },
    {
        id: 'WB0006',
        name: 'Md. Mamun Hasan',
        designation: 'Digital Marketing Specialist',
        image: 'https://res.cloudinary.com/dny7zfbg9/image/upload/v1738230846/iralz4f9oxtuaoudo4zg.jpg',
        description: `Mamun loves digital marketing and spends time creating strategic marketing plans. He also manages outreach efforts to help grow the company. His dedication plays a crucial role in expanding WebBriks' client base and services.`,
    },
    {
        id: 'WB0007',
        name: 'Golam Sarwar',
        designation: 'Senior Full Stack Web Developer',
        image: '/about/team-member/golam-sarwar.png',
        description: `Sarwar is passionate about building web applications and enjoys coding. He dedicates his time to creating smooth and efficient web solutions. He builds and maintains web applications with both front-end and back-end development.`,
    },
    {
        id: 'WB0007',
        name: 'Md. Salim Mia',
        designation: 'UI/UX Designer',
        image: '/about/team-member/salim-mia.png',
        description: `Salim is the Head of the Editing Team. He plays a key role in ensuring the delivery of final images to clients. His expertise and attention to detail guarantee that every project meets the highest standards.`,
    },
    {
        id: 'WB0010',
        name: 'Golam Sayed Sarker',
        designation: 'lead Generator',
        image: '/about/team-member/sayed-mia.png',
        description: `Sayeed works as a Marketing Assistant at WebBriks LLC. He focuses on collecting B2B leads for the business. He is highly talented and passionate about his work. His efforts play a key role in driving the company's growth and outreach.`,
    },
    {
        id: 'WB0010',
        name: 'Sohel Rana',
        designation: 'Video Editor',
        image: '/about/team-member/sohel-rana.png',
        description: `Rana creates videos for WebBriks and its clients, delivering excellent results. He enjoys the process of editing and bringing creative ideas to life. His dedication to quality helps produce engaging content that meets client needs.`,
    },
    {
        id: 'WB0009',
        name: 'Fuyad Hasan Fahim',
        designation: 'Full Stack Web Developer',
        image: 'https://res.cloudinary.com/dny7zfbg9/image/upload/v1738220314/p1ljpnndchofo0w6whak.jpg',
        description: `Fuyad is a full-stack web developer. He specializes in custom coding for websites. Fuyad ensures that every website is functional, efficient, and user-friendly.`,
    },
    {
        id: 'WB0024',
        name: 'Asanur Rahman',
        designation: 'Team Leader',
        image: '/about/team-member/ashanur-rahman.png',
        description: `Asanur leads a team dedicated to delivering high-quality image editing solutions for clients. His leadership ensures that every project is completed efficiently and meets client expectations.`,
    },
    {
        id: 'WB0012',
        name: 'Hiru Mia',
        designation: 'Team Leader',
        image: '/about/team-member/hiru-mia.png',
        bg: 'bg-[#DC143C]',
        ring: 'ring-[#DC143C]',
    },
    {
        id: 'WB0014',
        name: 'Md. Fazly Rabby',
        designation: 'Senior Photo Editor',
        image: '/about/team-member/fazle-rabby.png',
        bg: 'bg-[#1E90FF]',
        ring: 'ring-[#1E90FF]',
    },
    {
        id: 'WB0018',
        name: 'Benzir Ahamed',
        designation: 'Senior Photo Editor',
        image: '/about/team-member/benzir-ahmed.png',
        bg: 'bg-[#DA70D6]',
        ring: 'ring-[#DA70D6]',
    },
    {
        id: 'WB00',
        name: 'Md. Rayhan Babu',
        designation: 'Senior Photo Editor',
        image: '/about/team-member/rayhan-babu.png',
        bg: 'bg-[#FF4500]',
        ring: 'ring-[#FF4500]',
    },
    {
        id: 'WB0013',
        name: 'Kamal Pasha Pramanik',
        designation: 'Senior Photo Editor',
        image: '/about/team-member/kamal-pasha-pramanik.png',
        bg: 'bg-[#32CD32]',
        ring: 'ring-[#32CD32]',
    },
    {
        id: 'WB0016',
        name: 'Rezaul Alam Rana',
        designation: 'Senior Photo Editor',
        image: '/about/team-member/rezaul-alom.png',
        bg: 'bg-[#FA8072]',
        ring: 'ring-[#FA8072]',
    },
    {
        id: 'WB0026',
        name: 'Abdur Rajjak',
        designation: 'Photo Editor',
        image: '/about/team-member/abdur-razzak.png',
        bg: 'bg-[#FF6347]',
        ring: 'ring-[#FF6347]',
    },
    {
        id: 'WB0027',
        name: 'Abubokkor Siddiq',
        designation: 'Photo Editor',
        image: '/about/team-member/abubokkor-siddque.png',
        bg: 'bg-[#4682B4]',
        ring: 'ring-[#4682B4]',
    },
    {
        id: 'WB0027',
        name: 'Safin Mia',
        designation: 'Photo Editor',
        image: '/about/team-member/safin-mia.png',
        bg: 'bg-[#4682B4]',
        ring: 'ring-[#4682B4]',
    },
    {
        id: 'WB0034',
        name: 'Al Amin Mia',
        designation: 'Photo Editor',
        image: '/about/team-member/alamin-mia.png',
        bg: 'bg-[#FF1493]',
        ring: 'ring-[#FF1493]',
    },
    {
        id: 'WB0020',
        name: 'Beplob Miya',
        designation: 'Photo Editor',
        image: '/about/team-member/biplob-mia.png',
        bg: 'bg-[#FFB6C1]',
        ring: 'ring-[#FFB6C1]',
    },
    {
        id: 'WB0019',
        name: 'Fardous Ahammed',
        designation: 'Photo Editor',
        image: '/about/team-member/limon-mia.png',
        bg: 'bg-[#FFA07A]',
        ring: 'ring-[#FFA07A]',
    },
    {
        id: 'WB0028',
        name: 'Hasan Mahmud',
        designation: 'Photo Editor',
        image: '/about/team-member/hasan-mia.png',
        bg: 'bg-[#B0E0E6]',
        ring: 'ring-[#B0E0E6]',
    },
    {
        id: 'WB0021',
        name: 'Ashraful Islam',
        designation: 'Photo Editor',
        image: '/about/team-member/ashraful-islam-pramanik.png',
        bg: 'bg-[#FFDAB9]',
        ring: 'ring-[#FFDAB9]',
    },
    {
        id: 'WB0025',
        name: 'Shohel Rana',
        designation: 'Photo Editor',
        image: '/about/team-member/shohel-rana.png',
        bg: 'bg-[#2E8B57]',
        ring: 'ring-[#2E8B57]',
    },
    {
        id: 'WB0030',
        name: 'Moni Mia',
        designation: 'Photo Editor',
        image: '/about/team-member/moni-mia.png',
        bg: 'bg-[#FFA500]',
        ring: 'ring-[#FFA500]',
    },
    {
        id: 'WB0032',
        name: 'Nuralom Mia',
        designation: 'Photo Editor',
        image: '/about/team-member/nuralom-mia.png',
        bg: 'bg-[#800000]',
        ring: 'ring-[#800000]',
    },

    {
        id: 'WB0040',
        name: 'Sumon Ahmed',
        designation: 'Photo Editor',
        image: '/about/team-member/sumon-mia.png',
        bg: 'bg-[#FF8C00]',
        ring: 'ring-[#FF8C00]',
    },
    {
        id: 'WB0029',
        name: 'Masum kamal',
        designation: 'Junior Photo Editor',
        image: 'https://res.cloudinary.com/dny7zfbg9/image/upload/v1738226841/zrfsdlo7bivd2k0wsthg.jpg',
        bg: 'bg-[#6A5ACD]',
        ring: 'ring-[#6A5ACD]',
    },
    {
        id: 'WB0039',
        name: 'Abdul Kuddus',
        designation: 'Junior Photo Editor',
        image: '/about/team-member/abdul-kuddus-mia.png',
        bg: 'bg-[#87CEEB]',
        ring: 'ring-[#87CEEB]',
    },
    {
        id: 'WB0035',
        name: 'Al-amin Islam',
        designation: 'Junior Photo Editor',
        image: '/about/team-member/al-amin-mia.png',
        bg: 'bg-[#8A2BE2]',
        ring: 'ring-[#8A2BE2]',
    },
    {
        id: 'WB0036',
        name: 'Md. Belal Hosen',
        designation: 'Junior Photo Editor',
        image: '/about/team-member/belal-hosen.png',
        bg: 'bg-[#7FFF00]',
        ring: 'ring-[#7FFF00]',
    },
    {
        id: 'WB0031',
        name: 'Nahid Mia',
        designation: 'Junior Photo Editor',
        image: '/about/team-member/nahid-akondo.png',
        bg: 'bg-[#808080]',
        ring: 'ring-[#808080]',
    },
    {
        id: 'WB0033',
        name: 'Rana Mia',
        designation: 'Junior Photo Editor',
        image: '/about/team-member/rana-mia.png',
        bg: 'bg-[#CD5C5C]',
        ring: 'ring-[#CD5C5C]',
    },
    {
        id: 'WB0015',
        name: 'Md. Tauhidul Islam',
        designation: 'Junior Photo Editor',
        image: '/about/team-member/tawhidul-islam.png',
        bg: 'bg-[#20B2AA]',
        ring: 'ring-[#20B2AA]',
    },
    {
        id: 'WB0037',
        name: 'Shitol Mia',
        designation: 'Junior Photo Editor',
        image: '/about/team-member/shitol-mia.png',
        bg: 'bg-[#8B0000]',
        ring: 'ring-[#8B0000]',
    },
];
