export const teamMembers = [
    {
        id: 'WB0006',
        name: 'Md. Asaduzzaman',
        designation: 'CEO and Founder',
        image: '/about/boss/asad.png',
        bg: 'bg-[#FF5733]',
        ring: 'ring-[#FF5733]',
    },
    {
        id: 'WB0006',
        name: 'Md. Ariful Islam',
        designation: 'Co-Founder',
        image: '/about/boss/arif.png',
        bg: 'bg-[#FF5733]',
        ring: 'ring-[#FF5733]',
    },
    {
        id: 'WB0006',
        name: 'Md. Masum Kamal',
        designation: 'Co-Founder',
        image: '/about/boss/dulu.png',
        bg: 'bg-[#FF5733]',
        ring: 'ring-[#FF5733]',
    },
    {
        id: 'WB0006',
        name: 'Md. Kobir Hosain',
        designation: 'Co-Founder',
        image: '/about/boss/kobir.png',
        bg: 'bg-[#FF5733]',
        ring: 'ring-[#FF5733]',
    },
    {
        id: 'WB0005',
        name: 'Md. Oazed Akondo',
        designation: 'Office Admin',
        image: '/about/team-member/oazed-akondo.png',
        bg: 'bg-[#FF33A8]',
        ring: 'ring-[#FF33A8]',
    },
    {
        id: 'WB0006',
        name: 'Md. Mamun Hasan',
        designation: 'Head of Marketing',
        image: '/about/team-member/mamun-hasan.png',
        bg: 'bg-[#FF5733]',
        ring: 'ring-[#FF5733]',
    },
    {
        id: 'WB0007',
        name: 'Golam Sarwar',
        designation: 'Head of Web Development',
        image: '/about/team-member/golam-sarwar.png',
        bg: 'bg-[#33C1FF]',
        ring: 'ring-[#33C1FF]',
    },
    {
        id: 'WB0007',
        name: 'Md. Selim Mia',
        designation: 'Head of Photo Editing',
        image: '/about/team-member/salim-mia.png',
        bg: 'bg-[#33C1FF]',
        ring: 'ring-[#33C1FF]',
    },
    {
        id: 'WB0010',
        name: 'Golam Sayed Sarker',
        designation: 'Junior Marketer',
        image: '/about/team-member/sayed-mia.png',
        bg: 'bg-[#A833FF]',
        ring: 'ring-[#A833FF]',
    },
    {
        id: 'WB0010',
        name: 'Sohel Rana',
        designation: 'Junior Video Editor',
        image: '/about/team-member/sohel-rana.png',
        bg: 'bg-[#A833FF]',
        ring: 'ring-[#A833FF]',
    },
    {
        id: 'WB0009',
        name: 'Fuyad Hasan Fahim',
        designation: 'Full Stack Web Developer',
        image: '/about/team-member/fuyad-hasan-fahim.png',
        bg: 'bg-[#00FF7F]',
        ring: 'ring-[#00FF7F]',
    },
    {
        id: 'WB0024',
        name: 'Asanur Rahman',
        designation: 'Team Leader',
        image: '/about/team-member/ashanur-rahman.png',
        bg: 'bg-[#FF7F50]',
        ring: 'ring-[#FF7F50]',
    },
    {
        id: 'WB0014',
        name: 'Md. Fazly Rabby',
        designation: 'Senior Photo Editor',
        image: '/about/team-member/fazle-rabby.png',
        bg: 'bg-[#1E90FF]',
        ring: 'ring-[#1E90FF]',
    },
    {
        id: 'WB0018',
        name: 'Benzir Ahamed',
        designation: 'Senior Photo Editor',
        image: '/about/team-member/benzir-ahmed.png',
        bg: 'bg-[#DA70D6]',
        ring: 'ring-[#DA70D6]',
    },
    {
        id: 'WB00',
        name: 'Md. Rayhan Babu',
        designation: 'Senior Photo Editor',
        image: '/about/team-member/rayhan-babu.png',
        bg: 'bg-[#FF4500]',
        ring: 'ring-[#FF4500]',
    },
    {
        id: 'WB0013',
        name: 'Kamal Pasha Pramanik',
        designation: 'Senior Photo Editor',
        image: '/about/team-member/kamal-pasha-pramanik.png',
        bg: 'bg-[#32CD32]',
        ring: 'ring-[#32CD32]',
    },
    {
        id: 'WB0012',
        name: 'Hiru Mia',
        designation: 'Senior Photo Editor',
        image: '/about/team-member/hiru-mia.png',
        bg: 'bg-[#DC143C]',
        ring: 'ring-[#DC143C]',
    },
    {
        id: 'WB0016',
        name: 'Rezaul Alam Rana',
        designation: 'Senior Photo Editor',
        image: '/about/team-member/rezaul-alom.png',
        bg: 'bg-[#FA8072]',
        ring: 'ring-[#FA8072]',
    },
    {
        id: 'WB0026',
        name: 'Abdur Rajjak',
        designation: 'Photo Editor',
        image: '/about/team-member/abdur-razzak.png',
        bg: 'bg-[#FF6347]',
        ring: 'ring-[#FF6347]',
    },
    {
        id: 'WB0027',
        name: 'Abubokkor Siddiq',
        designation: 'Photo Editor',
        image: '/about/team-member/abubokkor-siddque.png',
        bg: 'bg-[#4682B4]',
        ring: 'ring-[#4682B4]',
    },
    {
        id: 'WB0027',
        name: 'Safin Mia',
        designation: 'Photo Editor',
        image: '/about/team-member/safin-mia.png',
        bg: 'bg-[#4682B4]',
        ring: 'ring-[#4682B4]',
    },
    {
        id: 'WB0034',
        name: 'Al Amin Mia',
        designation: 'Photo Editor',
        image: '/about/team-member/alamin-mia.png',
        bg: 'bg-[#FF1493]',
        ring: 'ring-[#FF1493]',
    },
    {
        id: 'WB0020',
        name: 'Beplob Miya',
        designation: 'Photo Editor',
        image: '/about/team-member/biplob-mia.png',
        bg: 'bg-[#FFB6C1]',
        ring: 'ring-[#FFB6C1]',
    },
    {
        id: 'WB0019',
        name: 'Fardous Ahammed',
        designation: 'Photo Editor',
        image: '/about/team-member/limon-mia.png',
        bg: 'bg-[#FFA07A]',
        ring: 'ring-[#FFA07A]',
    },
    {
        id: 'WB0028',
        name: 'Hasan Mahmud',
        designation: 'Photo Editor',
        image: '/about/team-member/hasan-mia.png',
        bg: 'bg-[#B0E0E6]',
        ring: 'ring-[#B0E0E6]',
    },
    {
        id: 'WB0021',
        name: 'Ashraful Islam',
        designation: 'Photo Editor',
        image: '/about/team-member/ashraful-islam-pramanik.png',
        bg: 'bg-[#FFDAB9]',
        ring: 'ring-[#FFDAB9]',
    },
    {
        id: 'WB0025',
        name: 'Shohel Rana',
        designation: 'Photo Editor',
        image: '/about/team-member/shohel-rana.png',
        bg: 'bg-[#2E8B57]',
        ring: 'ring-[#2E8B57]',
    },
    {
        id: 'WB0030',
        name: 'Moni Mia',
        designation: 'Photo Editor',
        image: '/about/team-member/moni-mia.png',
        bg: 'bg-[#FFA500]',
        ring: 'ring-[#FFA500]',
    },
    {
        id: 'WB0032',
        name: 'Nuralom Mia',
        designation: 'Photo Editor',
        image: '/about/team-member/nuralom-mia.png',
        bg: 'bg-[#800000]',
        ring: 'ring-[#800000]',
    },
    {
        id: 'WB0039',
        name: 'Abdul Kuddus',
        designation: 'Junior Photo Editor',
        image: '/about/team-member/abdul-kuddus-mia.png',
        bg: 'bg-[#87CEEB]',
        ring: 'ring-[#87CEEB]',
    },
    {
        id: 'WB0035',
        name: 'Al-amin Islam',
        designation: 'Junior Photo Editor',
        image: '/about/team-member/al-amin-mia.png',
        bg: 'bg-[#8A2BE2]',
        ring: 'ring-[#8A2BE2]',
    },
    {
        id: 'WB0036',
        name: 'Md. Belal Hosen',
        designation: 'Junior Photo Editor',
        image: '/about/team-member/belal-hosen.png',
        bg: 'bg-[#7FFF00]',
        ring: 'ring-[#7FFF00]',
    },
    {
        id: 'WB0029',
        name: 'Masum kamal',
        designation: 'Junior Photo Editor',
        image: '/about/team-member/masum-kamal.png',
        bg: 'bg-[#6A5ACD]',
        ring: 'ring-[#6A5ACD]',
    },
    {
        id: 'WB0031',
        name: 'Nahid Mia',
        designation: 'Junior Photo Editor',
        image: '/about/team-member/nahid-akondo.png',
        bg: 'bg-[#808080]',
        ring: 'ring-[#808080]',
    },
    {
        id: 'WB0033',
        name: 'Rana Mia',
        designation: 'Junior Photo Editor',
        image: '/about/team-member/rana-mia.png',
        bg: 'bg-[#CD5C5C]',
        ring: 'ring-[#CD5C5C]',
    },
    {
        id: 'WB0015',
        name: 'Md. Tauhidul Islam',
        designation: 'Junior Photo Editor',
        image: '/about/team-member/tawhidul-islam.png',
        bg: 'bg-[#20B2AA]',
        ring: 'ring-[#20B2AA]',
    },
    {
        id: 'WB0037',
        name: 'Shitol Mia',
        designation: 'Junior Photo Editor',
        image: '/about/team-member/shitol-mia.png',
        bg: 'bg-[#8B0000]',
        ring: 'ring-[#8B0000]',
    },
    {
        id: 'WB0040',
        name: 'Sumon Ahmed',
        designation: 'Photo Editor',
        image: '/about/team-member/sumon-mia.png',
        bg: 'bg-[#FF8C00]',
        ring: 'ring-[#FF8C00]',
    },
    {
        id: 'WB0041',
        name: 'Rayhan Mia',
        designation: 'Office Assistant',
        image: '/about/team-member/rayhan-mia.png',
        bg: 'bg-[#B22222]',
        ring: 'ring-[#B22222]',
    },
];
