import RootPricingPage from '@/components/pricing/RootPricingPage';

export const metadata = {
    title: 'Pricing | Webbriks',
    description: 'Generated by create next app',
};

export default async function page() {
    return <RootPricingPage />;
}
