import RootGraphicsDesign from '@/components/services/graphics-design/RootGraphicsDesign';

export const metadata = {
    title: 'Graphics Design Service | Webbriks',
    description: 'Generated by create next app',
};

export default async function page() {
    return <RootGraphicsDesign />;
}
