export const jobs = [
    {
        _id: '650f2b9c9d1f4a7e5b8c1234',
        title: 'Graphic Designer (International Brand Marketing)',
        company: 'Web Briks LLC',
        location: 'Mirpur-10, Dhaka',
        datePosted: '16 Sep, 2025',
        vacancies: 3,
        hasLogo: true,
        department: 'Graphics Design',
        notes: 'Age: 22 to 40 years',
        salary: 'Negotiable',
        experience:
            '2 to 5 years of proven experience in graphic design and brand design.',
        employmentStatus: 'Full-time (morning/evening shift)',
        workplace: 'Work at office',
        responsibilities: [
            'Develop unique and professional brand identities (logos, brand guidelines, etc.) for our company and clients.',
            'Design creative and impactful social media posts to promote our services to an international audience.',
            'Create marketing materials (banners, brochures, presentations, email templates, etc.) to support global campaigns.',
            'Collaborate with our marketing team to deliver designs that align with business objectives and appeal to international clients.',
            'Stay updated with the latest design trends, tools, and technologies to bring fresh, modern, and engaging concepts.',
            'Ensure all designs maintain high quality, creativity, and consistency with our brand guidelines.',
        ],
        requirements: [
            'Proven experience as a Graphic Designer with a portfolio showcasing creative and branding work.',
            'Expertise in Adobe Creative Suite (Photoshop, Illustrator, InDesign) and other relevant design tools.',
            'Strong understanding of international branding and digital marketing trends.',
            'Ability to think creatively and translate ideas into visually appealing designs.',
            'Excellent communication skills and a keen eye for detail.',
            'Previous experience designing for international clients or markets will be a strong advantage.',
            'Strong teamwork skills.',
        ],
        compensation: [
            'Yearly salary review.',
            'Two festival bonuses.',
            'Provident fund facilities.',
            'Weekly 2 holidays.',
            'Tour facilities.',
            'Opportunity to work on global projects and gain international exposure.',
            'Collaborative and growth-oriented work environment.',
        ],
        apply: {
            email: 'info@webbriks.com',
            subject: 'Application for Graphic Designer – Web Briks LLC',
        },
    },
    {
        _id: '650f2b9c9d1f4a7e5b8c5678',
        title: 'International Telemarketing Executive (Evening & Night Shift)',
        company: 'Web Briks LLC',
        location: 'Mirpur-10, Dhaka',
        datePosted: '16 Sep, 2025',
        vacancies: 6,
        hasLogo: true,
        department: 'Sales & Marketing',
        notes: 'Age: 18 to 35 years',
        salary: 'Tk. 18,000 - 25,000 (Monthly) + Performance Bonus',
        experience: '0 to 3 years (Freshers can apply)',
        employmentStatus: 'Full-time (Evening & Night Shift, Roster Duty)',
        workplace: 'Work at office',
        responsibilities: [
            'Making outbound calls to Europe & USA-Canada.',
            'Meet personal/team qualitative and quantitative targets.',
            'Convince clients to purchase our services.',
            'Onboard clients and bring revenue.',
            'Attend training sessions arranged by management.',
            'Ensure client’s payment after onboarding.',
            'Retain clients for the long term.',
        ],
        requirements: [
            'Fluent in English speaking with good command of vocabulary.',
            'Bachelor’s or Higher Secondary degree.',
            'O/A Levels, Bachelor’s in any discipline can apply.',
            'Proficient in Microsoft Excel & Word.',
            'Good accent with clear pronunciation is preferred.',
            'Self-motivated, hard-working, and proactive.',
            'Comfortable with multitasking in a deadline-driven environment.',
            'Familiarity with major social media platforms.',
        ],
        compensation: [
            '18k-25k salary + Performance Bonus.',
            'Yearly increment.',
            'Festival bonus.',
            'Snacks provided everyday.',
            'On-time payment.',
            'Beautiful office environment.',
            '2 weekly holidays (Saturday, Sunday).',
            'Women-friendly environment in both evening and night shift.',
            'Permanent employment after 4 months.',
            'KPI/sales bonus (earn 5-10k extra per month if targets are met).',
        ],
        apply: {
            email: 'info@webbriks.com',
            subject: 'Application for Telemarketer – Web Briks',
        },
    },
    {
        _id: '650f2b9c9d1f4a7e5b8c9876',
        title: 'Digital Marketing Specialist',
        company: 'Web Briks LLC',
        location: 'Mirpur-10, Dhaka',
        datePosted: '16 Sep, 2025',
        vacancies: 4,
        hasLogo: true,
        department: 'Digital Marketing',
        notes: 'Competitive, Negotiable (Based on experience & skills)',
        salary: 'Competitive, Negotiable',
        experience:
            '1–3 years in Digital Marketing (SEO & Social Media Marketing).',
        employmentStatus: 'Full-time (2 PM to 10:30 PM)',
        workplace: 'Work at office',
        responsibilities: [
            'Develop and execute comprehensive digital marketing strategies aligned with company goals and client objectives.',
            'Manage, optimize, and analyze paid advertising campaigns on Facebook, Google, LinkedIn, and YouTube.',
            'Oversee social media content creation, scheduling, and engagement.',
            'Conduct SEO and SEM activities to improve rankings and traffic.',
            'Create targeted content for digital channels (websites, blogs, emails, social media).',
            'Utilize analytics tools to track, measure, and report performance.',
            'Collaborate with creative teams for marketing materials and video content.',
            'Research and refine customer targeting through data-driven insights.',
            'Stay updated on digital marketing trends, AI tools, and technologies.',
            'Align marketing with sales and product teams for maximum ROI.',
        ],
        requirements: [
            "Bachelor's Degree in any discipline.",
            '1–3 years of Digital Marketing experience with SEO & Social Media expertise.',
            'Strong proficiency in Google Ads, Facebook Ads Manager, SEO/SEM tools, and analytics platforms.',
            'Basic graphic design skills (Photoshop, Illustrator).',
            'Knowledge of video editing and motion graphics is an advantage.',
            'Excellent English (written and verbal).',
            'Content writing and article writing in native English style (European & North American markets).',
            'Familiarity with AI-driven marketing tools (ChatGPT, Jasper, Copy.ai, MidJourney, DALL·E, Canva AI, SurferSEO, Frase, Clearscope, HubSpot, Mailchimp).',
            'Strong analytical and teamwork skills.',
        ],
        compensation: [
            'Competitive salary package (negotiable).',
            'Annual performance-based salary reviews.',
            'Two festival bonuses annually.',
            'Friendly and supportive work environment with career growth opportunities.',
            'Access to latest digital marketing and AI tools.',
            'Snacks provided everyday.',
            'Weekly holidays: Saturday & Sunday.',
        ],
        apply: {
            email: 'administration@aestheticeurasia.com',
            subject: 'Application – Digital Marketing Specialist',
        },
    },
];
