import RootServicesPage from '@/components/services/RootServicesPage';

export const metadata = {
    title: 'WebBriks Services: Creative Design & Photo Editing Services',
    description: 'Generated by create next app',
};

export default async function ServicePage() {
    return <RootServicesPage />;
}
