import RootPhotoEditingPage from '@/components/services/photo-editing/RootPhotoEditingPage';

export const metadata = {
    title: 'Photo Editing Service | Webbriks',
    description: 'Generated by create next app',
};

export default async function page() {
    return <RootPhotoEditingPage />;
}
